-- policy 1
GRANT SELECT ON AUDIT_LOG TO giulia_neri
GRANT SELECT ON AUDIT_LOG TO paolo_de_luca

--policy 2

CREATE OR REPLACE VIEW TOP_MANAGER_VIEW AS
SELECT e1.*
FROM EMPLOYEE e1
JOIN EMPLOYEE e2 ON e1.MANAGER_ID = e2.EMPLOYEE_ID
WHERE e2.ROLE_ID = 1 -- Top Manager
   OR e1.EMPLOYEE_ID IN (
       SELECT e3.EMPLOYEE_ID
       FROM EMPLOYEE e3
       JOIN EMPLOYEE e4 ON e3.MANAGER_ID = e4.EMPLOYEE_ID
       WHERE e4.ROLE_ID = 2 -- Middle Manager
   );


GRANT SELECT ON TOP_MANAGER_VIEW TO mario_rossi

--policy 3-4-5

CREATE OR REPLACE VIEW TOP_MANAGER_ALL_ACCOUNT_VIEW AS
SELECT
  e1.FISCAL_CODE,
  e1.NAME,
  e1.SURNAME,
  e1.EMAIL_ADDRESS AS HOLDER_EMAIL,
  e1.TEL_NO AS HOLDER_TEL_NO,
  e1.BIRTHDAY,
  e1.ACCOUNT_NO,
  e1.BAD_PAYER,
  e1.TYPE_WORK,
  e3.OWNER_CODE,
  e3.BALANCE,
  e2.CARD_NO,
  e2.CARD_TYPE,
  e2.PAYMENT_CIRCUIT,
  e2.LIMIT,
  e2.FLAG_ACTIVE,
  e2.EXPIRATION_DATE,
  e1.EMPLOYEE_ID,
  e4.USERNAME AS EMPLOYEE_USERNAME,
  e4.MAIL_ADDRESS AS EMPLOYEE_EMAIL,
  e4.TEL_NO AS EMPLOYEE_TEL_NO
 
FROM ACCOUNT_HOLDER e1
LEFT JOIN CURRENT_ACCOUNT e3 on e1.ACCOUNT_NO = e3.ACCOUNT_NO
LEFT JOIN CARD e2 ON e1.ACCOUNT_NO = e2.ACCOUNT_NO
--LEFT JOIN TRANSACTION e3 ON e1.ACCOUNT_NO = e3.ACCOUNT_NO
LEFT JOIN EMPLOYEE e4 ON e1.EMPLOYEE_ID = e4.EMPLOYEE_ID;
 
 
GRANT SELECT ON TOP_MANAGER_ALL_ACCOUNT_VIEW TO mario_rossi;


--policy 6

CREATE OR REPLACE VIEW TOP_MANAGER_TRANSACTION_VIEW AS
SELECT t.*
FROM TRANSACTION t
JOIN EMPLOYEE cashier ON t.EMPLOYEE_ID = cashier.EMPLOYEE_ID
WHERE cashier.MANAGER_ID IN ( -- Middle Manager
    SELECT mm.EMPLOYEE_ID
    FROM EMPLOYEE mm
    WHERE mm.MANAGER_ID IN ( -- Top Manager
        SELECT tm.EMPLOYEE_ID
        FROM EMPLOYEE tm
        WHERE tm.ROLE_ID = 1
    )
);

GRANT SELECT ON TOP_MANAGER_TRANSACTION_VIEW TO mario_rossi;

--policy 7

GRANT INSERT, UPDATE, DELETE ON ACCOUNT_HOLDER TO mario_rossi;

--policy 8

GRANT UPDATE (MANAGER_ID) ON EMPLOYEE TO mario_rossi;

--policy 9
CREATE OR REPLACE VIEW MIDDLE_MANAGER_1_VIEW AS
SELECT e1.*
FROM EMPLOYEE e1
JOIN EMPLOYEE e2 ON e1.MANAGER_ID = e2.EMPLOYEE_ID
WHERE (e2.EMPLOYEE_ID = 2 AND e1.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 2))  -- Middle Manager 1 può vedere Employee ID 3, 5, 6 (Cassieri)
   OR (e2.EMPLOYEE_ID = 1 AND e1.EMPLOYEE_ID = 2)  -- Per vedere il Middle Manager 1 stesso


CREATE OR REPLACE VIEW MIDDLE_MANAGER_2_VIEW AS
SELECT e1.*
FROM EMPLOYEE e1
JOIN EMPLOYEE e2 ON e1.MANAGER_ID = e2.EMPLOYEE_ID
WHERE (e2.EMPLOYEE_ID = 5 AND e1.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 5))  -- Middle Manager 2 può vedere Employee ID 9, 10
   OR (e2.EMPLOYEE_ID = 5 AND e1.EMPLOYEE_ID = 5) -- Per vedere il Middle Manager 2 stesso


GRANT SELECT ON MIDDLE_MANAGER_1_VIEW TO luca_bianchi

GRANT SELECT ON MIDDLE_MANAGER_2_VIEW TO stefano_moretti

--policy 10-12-13

CREATE OR REPLACE VIEW MIDDLE_MANAGER_1_ACCOUNT_VIEW AS
SELECT
  ah.FISCAL_CODE,
  ah.NAME,
  ah.SURNAME,
  ah.EMAIL_ADDRESS AS HOLDER_EMAIL,
  ah.TEL_NO AS HOLDER_TEL_NO,
  ah.BIRTHDAY,
  ah.ACCOUNT_NO,
  ah.BAD_PAYER,
  ah.TYPE_WORK,
  ca.OWNER_CODE,
  ca.BALANCE,
  cr.CARD_NO,
  cr.CARD_TYPE,
  cr.PAYMENT_CIRCUIT,
  cr.LIMIT,
  cr.FLAG_ACTIVE,
  cr.EXPIRATION_DATE,
  mm.EMPLOYEE_ID AS MIDDLE_MANAGER_ID,
  mm.USERNAME AS MIDDLE_MANAGER_USERNAME,
  mm.MAIL_ADDRESS AS MIDDLE_MANAGER_EMAIL,
  mm.TEL_NO AS MIDDLE_MANAGER_TEL_NO
FROM ACCOUNT_HOLDER ah
LEFT JOIN CURRENT_ACCOUNT ca ON ah.ACCOUNT_NO = ca.ACCOUNT_NO
LEFT JOIN CARD cr ON ah.ACCOUNT_NO = cr.ACCOUNT_NO
LEFT JOIN EMPLOYEE cashier ON ah.EMPLOYEE_ID = cashier.EMPLOYEE_ID
LEFT JOIN EMPLOYEE mm
    ON cashier.MANAGER_ID = mm.EMPLOYEE_ID
   AND mm.EMPLOYEE_ID = 2
WHERE cashier.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 2);
 
 
GRANT SELECT ON TOP_MANAGER_ALL_ACCOUNT_VIEW TO luca_bianchi;
 
 
CREATE OR REPLACE VIEW MIDDLE_MANAGER_2_ACCOUNT_VIEW AS
SELECT
  ah.FISCAL_CODE,
  ah.NAME,
  ah.SURNAME,
  ah.EMAIL_ADDRESS AS HOLDER_EMAIL,
  ah.TEL_NO AS HOLDER_TEL_NO,
  ah.BIRTHDAY,
  ah.ACCOUNT_NO,
  ah.BAD_PAYER,
  ah.TYPE_WORK,
  ca.OWNER_CODE,
  ca.BALANCE,
  cr.CARD_NO,
  cr.CARD_TYPE,
  cr.PAYMENT_CIRCUIT,
  cr.LIMIT,
  cr.FLAG_ACTIVE,
  cr.EXPIRATION_DATE,
  mm.EMPLOYEE_ID AS MIDDLE_MANAGER_ID,
  mm.USERNAME AS MIDDLE_MANAGER_USERNAME,
  mm.MAIL_ADDRESS AS MIDDLE_MANAGER_EMAIL,
  mm.TEL_NO AS MIDDLE_MANAGER_TEL_NO
FROM ACCOUNT_HOLDER ah
LEFT JOIN CURRENT_ACCOUNT ca ON ah.ACCOUNT_NO = ca.ACCOUNT_NO
LEFT JOIN CARD cr ON ah.ACCOUNT_NO = cr.ACCOUNT_NO
LEFT JOIN EMPLOYEE cashier ON ah.EMPLOYEE_ID = cashier.EMPLOYEE_ID
LEFT JOIN EMPLOYEE mm
    ON cashier.MANAGER_ID = mm.EMPLOYEE_ID
   AND mm.EMPLOYEE_ID = 5
WHERE cashier.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 5);
 
 
GRANT SELECT ON TOP_MANAGER_ALL_ACCOUNT_VIEW TO stefano_moretti;

--policy 11

GRANT INSERT, UPDATE, DELETE ON ACCOUNT_HOLDER TO luca_bianchi;
GRANT INSERT, UPDATE, DELETE ON ACCOUNT_HOLDER TO stefano_moretti;


--policy 14

CREATE OR REPLACE VIEW MIDDLE_MANAGER_1_TRANSACTION_VIEW AS
SELECT t.*
FROM TRANSACTION t
JOIN EMPLOYEE cashier ON t.EMPLOYEE_ID = cashier.EMPLOYEE_ID
WHERE cashier.MANAGER_ID = 2;


CREATE OR REPLACE VIEW MIDDLE_MANAGER_5_TRANSACTION_VIEW AS
SELECT t.*
FROM TRANSACTION t
JOIN EMPLOYEE cashier ON t.EMPLOYEE_ID = cashier.EMPLOYEE_ID
WHERE cashier.MANAGER_ID = 5;




GRANT SELECT ON MIDDLE_MANAGER_2_TRANSACTION_VIEW TO luca_bianchi;
GRANT SELECT ON MIDDLE_MANAGER_5_TRANSACTION_VIEW TO stefano_moretti;


--policy 15

CREATE OR REPLACE VIEW CASHIER_MM1_ACCOUNT_VIEW AS
SELECT
  ah.FISCAL_CODE,
  ah.NAME,
  ah.SURNAME,
  ah.EMAIL_ADDRESS AS HOLDER_EMAIL,
  ah.TEL_NO AS HOLDER_TEL_NO,
  ah.BIRTHDAY,
  ah.ACCOUNT_NO,
  ca.BALANCE,
  cr.CARD_NO,
  mm.EMPLOYEE_ID AS MIDDLE_MANAGER_ID,
  mm.USERNAME AS MIDDLE_MANAGER_USERNAME,
  mm.MAIL_ADDRESS AS MIDDLE_MANAGER_EMAIL,
  mm.TEL_NO AS MIDDLE_MANAGER_TEL_NO
FROM ACCOUNT_HOLDER ah
LEFT JOIN CURRENT_ACCOUNT ca ON ah.ACCOUNT_NO = ca.ACCOUNT_NO
LEFT JOIN CARD cr ON ah.ACCOUNT_NO = cr.ACCOUNT_NO
LEFT JOIN EMPLOYEE cashier ON ah.EMPLOYEE_ID = cashier.EMPLOYEE_ID
LEFT JOIN EMPLOYEE mm
    ON cashier.MANAGER_ID = mm.EMPLOYEE_ID
   AND mm.EMPLOYEE_ID = 2
WHERE cashier.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 2);


CREATE OR REPLACE VIEW CASHIER_MM2_ACCOUNT_VIEW AS
SELECT
  ah.FISCAL_CODE,
  ah.NAME,
  ah.SURNAME,
  ah.EMAIL_ADDRESS AS HOLDER_EMAIL,
  ah.TEL_NO AS HOLDER_TEL_NO,
  ah.BIRTHDAY,
  ah.ACCOUNT_NO,
  ca.BALANCE,
  cr.CARD_NO,
  mm.EMPLOYEE_ID AS MIDDLE_MANAGER_ID,
  mm.USERNAME AS MIDDLE_MANAGER_USERNAME,
  mm.MAIL_ADDRESS AS MIDDLE_MANAGER_EMAIL,
  mm.TEL_NO AS MIDDLE_MANAGER_TEL_NO
FROM ACCOUNT_HOLDER ah
LEFT JOIN CURRENT_ACCOUNT ca ON ah.ACCOUNT_NO = ca.ACCOUNT_NO
LEFT JOIN CARD cr ON ah.ACCOUNT_NO = cr.ACCOUNT_NO
LEFT JOIN EMPLOYEE cashier ON ah.EMPLOYEE_ID = cashier.EMPLOYEE_ID
LEFT JOIN EMPLOYEE mm
    ON cashier.MANAGER_ID = mm.EMPLOYEE_ID
   AND mm.EMPLOYEE_ID = 5
WHERE cashier.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 5);

GRANT SELECT ON CASHIER_MM1_ACCOUNT_VIEW TO anna_verdi
GRANT SELECT ON CASHIER_MM1_ACCOUNT_VIEW TO elisa_conti
GRANT SELECT ON CASHIER_MM1_ACCOUNT_VIEW TO francesco_ricci


GRANT SELECT ON CASHIER_MM2_ACCOUNT_VIEW TO martina_ferrari
GRANT SELECT ON CASHIER_MM2_ACCOUNT_VIEW TO alessandro_romano


--policy 16

CREATE OR REPLACE VIEW CASHIER_MM1_VIEW AS
SELECT e1.EMPLOYEE_ID, e1.NAME, e1.SURNAME, e1.HIRE_DATE, e1.MAIL_ADDRESS, e1.TEL_NO, e1.ROLE_ID, e1.MANAGER_ID
FROM EMPLOYEE e1
WHERE e1.ROLE_ID = 3  -- Solo Cassieri
  AND (e1.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 2)  -- I Cassieri sotto il Middle Manager 1
       OR e1.MANAGER_ID = 2);  -- Cassieri sotto il Middle Manager 1 (con Manager ID = 2)


CREATE OR REPLACE VIEW CASHIER_MM2_VIEW AS
SELECT e1.EMPLOYEE_ID, e1.NAME, e1.SURNAME, e1.HIRE_DATE, e1.MAIL_ADDRESS, e1.TEL_NO, e1.ROLE_ID, e1.MANAGER_ID
FROM EMPLOYEE e1
WHERE e1.ROLE_ID = 3  -- Solo Cassieri
  AND (e1.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 5)  -- I Cassieri sotto il Middle Manager 2
       OR e1.MANAGER_ID = 5);  -- Cassieri sotto il Middle Manager 2 (con Manager ID = 5)


GRANT SELECT ON CASHIER_MM1_VIEW TO anna_verdi
GRANT SELECT ON CASHIER_MM1_VIEW TO elisa_conti
GRANT SELECT ON CASHIER_MM1_VIEW TO francesco_ricci


GRANT SELECT ON CASHIER_MM2_VIEW TO martina_ferrari
GRANT SELECT ON CASHIER_MM2_VIEW TO alessandro_romano


