--policy 2
CREATE OR REPLACE VIEW TOP_MANAGER_VIEW AS
SELECT e1.*
FROM EMPLOYEE e1
JOIN EMPLOYEE e2 ON e1.MANAGER_ID = e2.EMPLOYEE_ID
WHERE e2.ROLE_ID = 1 -- Top Manager
   OR e1.EMPLOYEE_ID IN (
       SELECT e3.EMPLOYEE_ID
       FROM EMPLOYEE e3
       JOIN EMPLOYEE e4 ON e3.MANAGER_ID = e4.EMPLOYEE_ID
       WHERE e4.ROLE_ID = 2 -- Middle Manager
   );

CREATE ROLE top_manager;
GRANT SELECT ON TOP_MANAGER_VIEW TO top_manager;
GRANT top_manager TO mario_rossi;

--policy 3-4-5
CREATE OR REPLACE VIEW TOP_MANAGER_ALL_ACCOUNT_VIEW AS
SELECT
  e1.FISCAL_CODE,
  e1.NAME,
  e1.SURNAME,
  e1.EMAIL_ADDRESS AS HOLDER_EMAIL,
  e1.TEL_NO AS HOLDER_TEL_NO,
  e1.BIRTHDAY,
  e1.ACCOUNT_NO,
  e1.BAD_PAYER,
  e1.TYPE_WORK,
  e3.OWNER_CODE,
  e3.BALANCE,
  e2.CARD_NO,
  e2.CARD_TYPE,
  e2.PAYMENT_CIRCUIT,
  e2.LIMIT,
  e2.FLAG_ACTIVE,
  e2.EXPIRATION_DATE,
  e1.EMPLOYEE_ID,
  e4.USERNAME AS EMPLOYEE_USERNAME,
  e4.MAIL_ADDRESS AS EMPLOYEE_EMAIL,
  e4.TEL_NO AS EMPLOYEE_TEL_NO
 
FROM ACCOUNT_HOLDER e1
LEFT JOIN CURRENT_ACCOUNT e3 on e1.ACCOUNT_NO = e3.ACCOUNT_NO
LEFT JOIN CARD e2 ON e1.ACCOUNT_NO = e2.ACCOUNT_NO
LEFT JOIN EMPLOYEE e4 ON e1.EMPLOYEE_ID = e4.EMPLOYEE_ID;

GRANT SELECT ON TOP_MANAGER_ALL_ACCOUNT_VIEW TO top_manager;

--policy 6
CREATE OR REPLACE VIEW TOP_MANAGER_TRANSACTION_VIEW AS
SELECT t.*
FROM TRANSACTION t
JOIN EMPLOYEE cashier ON t.EMPLOYEE_ID = cashier.EMPLOYEE_ID
WHERE cashier.MANAGER_ID IN ( -- Middle Manager
    SELECT mm.EMPLOYEE_ID
    FROM EMPLOYEE mm
    WHERE mm.MANAGER_ID IN ( -- Top Manager
        SELECT tm.EMPLOYEE_ID
        FROM EMPLOYEE tm
        WHERE tm.ROLE_ID = 1
    )
);

GRANT SELECT ON TOP_MANAGER_TRANSACTION_VIEW TO top_manager;
--policy 7
GRANT INSERT, UPDATE, DELETE ON ACCOUNT_HOLDER TO top_manager;

--policy 8
GRANT UPDATE (MANAGER_ID) ON EMPLOYEE TO top_manager;
--policy 9
CREATE OR REPLACE VIEW MIDDLE_MANAGER_1_VIEW AS
SELECT e1.*
FROM EMPLOYEE e1
JOIN EMPLOYEE e2 ON e1.MANAGER_ID = e2.EMPLOYEE_ID
WHERE (e2.EMPLOYEE_ID = 2 AND e1.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 2))  -- Middle Manager 1 può vedere Employee ID 3, 5, 6 (Cassieri)
   OR (e2.EMPLOYEE_ID = 1 AND e1.EMPLOYEE_ID = 2);  -- Per vedere il Middle Manager 1 stesso

CREATE OR REPLACE VIEW MIDDLE_MANAGER_2_VIEW AS
SELECT e1.*
FROM EMPLOYEE e1
JOIN EMPLOYEE e2 ON e1.MANAGER_ID = e2.EMPLOYEE_ID
WHERE (e2.EMPLOYEE_ID = 5 AND e1.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 5))  -- Middle Manager 2 può vedere Employee ID 9, 10
   OR (e2.EMPLOYEE_ID = 5 AND e1.EMPLOYEE_ID = 5); -- Per vedere il Middle Manager 2 stesso

CREATE ROLE middle_manager_1;
CREATE ROLE middle_manager_2;

GRANT middle_manager_1 TO luca_bianchi;
GRANT middle_manager_2 TO stefano_moretti;

GRANT SELECT ON MIDDLE_MANAGER_1_VIEW TO middle_manager_1;
GRANT SELECT ON MIDDLE_MANAGER_2_VIEW TO middle_manager_2;

--policy 10-12-13

CREATE OR REPLACE VIEW MIDDLE_MANAGER_1_ACCOUNT_VIEW AS
SELECT
  ah.FISCAL_CODE,
  ah.NAME,
  ah.SURNAME,
  ah.EMAIL_ADDRESS AS HOLDER_EMAIL,
  ah.TEL_NO AS HOLDER_TEL_NO,
  ah.BIRTHDAY,
  ah.ACCOUNT_NO,
  ah.BAD_PAYER,
  ah.TYPE_WORK,
  ca.OWNER_CODE,
  ca.BALANCE,
  cr.CARD_NO,
  cr.CARD_TYPE,
  cr.PAYMENT_CIRCUIT,
  cr.LIMIT,
  cr.FLAG_ACTIVE,
  cr.EXPIRATION_DATE,
  mm.EMPLOYEE_ID AS MIDDLE_MANAGER_ID,
  mm.USERNAME AS MIDDLE_MANAGER_USERNAME,
  mm.MAIL_ADDRESS AS MIDDLE_MANAGER_EMAIL,
  mm.TEL_NO AS MIDDLE_MANAGER_TEL_NO
FROM ACCOUNT_HOLDER ah
LEFT JOIN CURRENT_ACCOUNT ca ON ah.ACCOUNT_NO = ca.ACCOUNT_NO
LEFT JOIN CARD cr ON ah.ACCOUNT_NO = cr.ACCOUNT_NO
LEFT JOIN EMPLOYEE cashier ON ah.EMPLOYEE_ID = cashier.EMPLOYEE_ID
LEFT JOIN EMPLOYEE mm
    ON cashier.MANAGER_ID = mm.EMPLOYEE_ID
   AND mm.EMPLOYEE_ID = 2
WHERE cashier.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 2);

GRANT SELECT ON MIDDLE_MANAGER_1_ACCOUNT_VIEW TO middle_manager_1;
 
CREATE OR REPLACE VIEW MIDDLE_MANAGER_2_ACCOUNT_VIEW AS
SELECT
  ah.FISCAL_CODE,
  ah.NAME,
  ah.SURNAME,
  ah.EMAIL_ADDRESS AS HOLDER_EMAIL,
  ah.TEL_NO AS HOLDER_TEL_NO,
  ah.BIRTHDAY,
  ah.ACCOUNT_NO,
  ah.BAD_PAYER,
  ah.TYPE_WORK,
  ca.OWNER_CODE,
  ca.BALANCE,
  cr.CARD_NO,
  cr.CARD_TYPE,
  cr.PAYMENT_CIRCUIT,
  cr.LIMIT,
  cr.FLAG_ACTIVE,
  cr.EXPIRATION_DATE,
  mm.EMPLOYEE_ID AS MIDDLE_MANAGER_ID,
  mm.USERNAME AS MIDDLE_MANAGER_USERNAME,
  mm.MAIL_ADDRESS AS MIDDLE_MANAGER_EMAIL,
  mm.TEL_NO AS MIDDLE_MANAGER_TEL_NO
FROM ACCOUNT_HOLDER ah
LEFT JOIN CURRENT_ACCOUNT ca ON ah.ACCOUNT_NO = ca.ACCOUNT_NO
LEFT JOIN CARD cr ON ah.ACCOUNT_NO = cr.ACCOUNT_NO
LEFT JOIN EMPLOYEE cashier ON ah.EMPLOYEE_ID = cashier.EMPLOYEE_ID
LEFT JOIN EMPLOYEE mm
    ON cashier.MANAGER_ID = mm.EMPLOYEE_ID
   AND mm.EMPLOYEE_ID = 5
WHERE cashier.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MANAGER_ID = 5);
 

GRANT SELECT ON MIDDLE_MANAGER_2_ACCOUNT_VIEW TO middle_manager_2;
GRANT INSERT, UPDATE, DELETE ON ACCOUNT_HOLDER TO middle_manager_1;
GRANT INSERT, UPDATE, DELETE ON ACCOUNT_HOLDER TO middle_manager_2;

--policy 14
CREATE OR REPLACE VIEW MIDDLE_MANAGER_1_TRANSACTION_VIEW AS
SELECT t.*
FROM TRANSACTION t
JOIN EMPLOYEE cashier ON t.EMPLOYEE_ID = cashier.EMPLOYEE_ID
WHERE cashier.MANAGER_ID = 2;


CREATE OR REPLACE VIEW MIDDLE_MANAGER_5_TRANSACTION_VIEW AS
SELECT t.*
FROM TRANSACTION t
JOIN EMPLOYEE cashier ON t.EMPLOYEE_ID = cashier.EMPLOYEE_ID
WHERE cashier.MANAGER_ID = 5;

GRANT SELECT ON MIDDLE_MANAGER_2_TRANSACTION_VIEW TO middle_manager_1;
GRANT SELECT ON MIDDLE_MANAGER_5_TRANSACTION_VIEW TO middle_manager_2;

--policy 15

CREATE OR REPLACE VIEW CASHIER_ACCOUNT_VIEW AS
SELECT
  ah.FISCAL_CODE,
  ah.NAME,
  ah.SURNAME,
  ah.EMAIL_ADDRESS AS HOLDER_EMAIL,
  ah.TEL_NO AS HOLDER_TEL_NO,
  ah.BIRTHDAY,
  ah.ACCOUNT_NO,
  ca.BALANCE,
  cr.CARD_NO,
  mm.EMPLOYEE_ID AS MIDDLE_MANAGER_ID,
  mm.USERNAME AS MIDDLE_MANAGER_USERNAME,
  mm.MAIL_ADDRESS AS MIDDLE_MANAGER_EMAIL,
  mm.TEL_NO AS MIDDLE_MANAGER_TEL_NO
FROM ACCOUNT_HOLDER ah
LEFT JOIN CURRENT_ACCOUNT ca ON ah.ACCOUNT_NO = ca.ACCOUNT_NO
LEFT JOIN CARD cr ON ah.ACCOUNT_NO = cr.ACCOUNT_NO
LEFT JOIN EMPLOYEE cashier ON ah.EMPLOYEE_ID = cashier.EMPLOYEE_ID
LEFT JOIN EMPLOYEE mm
    ON cashier.MANAGER_ID = mm.EMPLOYEE_ID
WHERE cashier.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEE);

GRANT cashier TO anna_verdi;
GRANT cashier TO elisa_conti;
GRANT cashier TO francesco_ricci;
GRANT cashier TO martina_ferrari;
GRANT cashier TO alessandro_romano;
GRANT SELECT ON CASHIER_ACCOUNT_VIEW TO cashier;

--policy 16

CREATE OR REPLACE VIEW CASHIER_VIEW AS
SELECT e1.EMPLOYEE_ID, e1.NAME, e1.SURNAME, e1.HIRE_DATE, e1.MAIL_ADDRESS, e1.TEL_NO, e1.ROLE_ID, e1.MANAGER_ID
FROM EMPLOYEE e1
WHERE e1.ROLE_ID = 3;  -- Solo Cassieri

GRANT SELECT ON CASHIER_VIEW TO cashier;
